In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data_Smote = pd.read_csv('Traindata_clean.csv')

In [3]:
data_Smote[:5]

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
0                 0                              0.766127   45   
1                 1                              0.957151   40   
2                 1                              0.658180   38   
3                 1                              0.233810   30   
4                 1                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0   
1                                     0   0.121876         2600.0   
2                                     1   0.085113         3042.0   
3                                     0   0.036050         3300.0   
4                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0   
1                                4                        0   
2                                2                        1   
3                                5                        0   
4                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0   
1                             0                                     0   
2                             0                                     0   
3                             0                                     0   
4                             1                                     0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [4]:
data_Smote.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145837 entries, 0 to 145836
Data columns (total 11 columns):
SeriousDlqin2yrs                        145837 non-null int64
RevolvingUtilizationOfUnsecuredLines    145837 non-null float64
age                                     145837 non-null int64
NumberOfTime30-59DaysPastDueNotWorse    145837 non-null int64
DebtRatio                               145837 non-null float64
MonthlyIncome                           145837 non-null float64
NumberOfOpenCreditLinesAndLoans         145837 non-null int64
NumberOfTimes90DaysLate                 145837 non-null int64
NumberRealEstateLoansOrLines            145837 non-null int64
NumberOfTime60-89DaysPastDueNotWorse    145837 non-null int64
NumberOfDependents                      145837 non-null float64
dtypes: float64(4), int64(7)
memory usage: 12.2 MB


# 分箱的三种方法
1. 等频分箱
2. 等距分箱
3. 基于k均值聚类的分箱

In [5]:
print(data_Smote['RevolvingUtilizationOfUnsecuredLines'].unique())
print('RevolvingUtilizationOfUnsecuredLines',data_Smote['RevolvingUtilizationOfUnsecuredLines'].unique().shape)
print(data_Smote['age'].unique())
print('age',data_Smote['age'].unique().shape)
print(data_Smote['NumberOfTime30-59DaysPastDueNotWorse'].unique())
print('NumberOfTime30-59DaysPastDueNotWorse',data_Smote['NumberOfTime30-59DaysPastDueNotWorse'].unique().shape)
print(data_Smote['DebtRatio'].unique())
print('DebtRatio',data_Smote['DebtRatio'].unique().shape)
print(data_Smote['MonthlyIncome'].unique())
print('MonthlyIncome',data_Smote['MonthlyIncome'].unique().shape)
print(data_Smote['NumberOfOpenCreditLinesAndLoans'].unique())
print('NumberOfOpenCreditLinesAndLoans',data_Smote['NumberOfOpenCreditLinesAndLoans'].unique().shape)
print(data_Smote['NumberOfTimes90DaysLate'].unique())
print('NumberOfTimes90DaysLate',data_Smote['NumberOfTimes90DaysLate'].unique().shape)
print(data_Smote['NumberRealEstateLoansOrLines'].unique())
print('NumberRealEstateLoansOrLines',data_Smote['NumberRealEstateLoansOrLines'].unique().shape)
print(data_Smote['NumberOfTime60-89DaysPastDueNotWorse'].unique())
print('NumberOfTime60-89DaysPastDueNotWorse',data_Smote['NumberOfTime60-89DaysPastDueNotWorse'].unique().shape)
print(data_Smote['NumberOfDependents'].unique())
print('NumberOfDependents',data_Smote['NumberOfDependents'].unique().shape)

[0.76612661 0.95715102 0.65818014 ... 0.29974515 0.24604392 0.85028295]
RevolvingUtilizationOfUnsecuredLines (122957,)
[ 45  40  38  30  49  74  57  39  51  46  76  64  78  53  43  25  32  58
  50  69  24  28  62  42  75  26  52  41  81  31  68  70  73  29  55  35
  72  60  67  27  36  56  37  66  83  34  44  61  80  47  59  77  48  63
  54  33  79  65  86  92  23  87  71  90  84  82  22  89  91  85  88  21
  93  96  94  95 101  97  98 103 102  99 107]
age (83,)
[ 2  0  1  3  4  5  7 10  6 12  8  9 13 11]
NumberOfTime30-59DaysPastDueNotWorse (14,)
[0.80298213 0.1218762  0.08511338 ... 0.40429286 0.71656222 0.24990808]
DebtRatio (114069,)
[9.12000000e+03 2.60000000e+03 3.04200000e+03 ... 1.22229307e+01
 7.64700000e+03 4.03355074e-01]
MonthlyIncome (17359,)
[13  4  2  5  7  3  8  9  6 10 14 22 17  1 15 31 12 21 11 19 18 26 20 23
  0 16 27 29 28 24 25 32 46 33 30 34 37 38 36 35 54 43 45 49 57 48 40 58
 51 52 39 41 56 42 47 50 44 53]
NumberOfOpenCreditLinesAndLoans (58,)
[ 0  1  3  2  5  4

In [6]:
data_Smote.columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

## 第一种 等距分箱

In [7]:
bins_ROUL =[-np.inf,0,0.3,0.7,1,3,np.inf]  # RevolvingUtilizationOfUnsecuredLines
bins_age =[-np.inf,30,45,55,60,65,75,np.inf]  # age
bins_N359DW = [-np.inf,0,1,3,5,np.inf]  # NumberOfTime30-59DaysPastDueNotWorse
bins_Ratio = [-np.inf,0,1,3,5,10,np.inf]   # DebtRatio
bins_moncome =[-np.inf,751,3000,4500,6100,8850,np.inf] # MonthlyIncome
bins_NCLL =[-np.inf,0,1,3,5,np.inf] # NumberOfOpenCreditLinesAndLoans
bins_N90DL = [-np.inf,0,1,2,5,np.inf]   # NumberOfTimes90DaysLate
bins_NRLL = [-np.inf,1,2,np.inf]   # NumberRealEstateLoansOrLines
bins_N689DW = [-np.inf,0,1,3,5,np.inf]  # NumberOfTime60-89DaysPastDueNotWorse
bins_NOD =[-np.inf,0,1,3,5,np.inf] # NumberOfDependents
bins_seq ={}

In [8]:
for name,bins in zip(list(data_Smote.columns)[1:],[bins_ROUL,bins_age,bins_N359DW,bins_Ratio,bins_moncome,bins_NCLL,bins_N90DL,bins_NRLL,bins_N689DW,bins_NOD]):
    bins_seq[name] = bins

In [9]:
pd.cut(data_Smote['NumberOfDependents'],bins=bins_NOD).value_counts()

(-inf, 0.0]    86714
(1.0, 3.0]     28980
(0.0, 1.0]     26293
(3.0, 5.0]      3605
(5.0, inf]       245
Name: NumberOfDependents, dtype: int64

In [10]:
bins_seq

{'RevolvingUtilizationOfUnsecuredLines': [-inf, 0, 0.3, 0.7, 1, 3, inf],
 'age': [-inf, 30, 45, 55, 60, 65, 75, inf],
 'NumberOfTime30-59DaysPastDueNotWorse': [-inf, 0, 1, 3, 5, inf],
 'DebtRatio': [-inf, 0, 1, 3, 5, 10, inf],
 'MonthlyIncome': [-inf, 751, 3000, 4500, 6100, 8850, inf],
 'NumberOfOpenCreditLinesAndLoans': [-inf, 0, 1, 3, 5, inf],
 'NumberOfTimes90DaysLate': [-inf, 0, 1, 2, 5, inf],
 'NumberRealEstateLoansOrLines': [-inf, 1, 2, inf],
 'NumberOfTime60-89DaysPastDueNotWorse': [-inf, 0, 1, 3, 5, inf],
 'NumberOfDependents': [-inf, 0, 1, 3, 5, inf]}

# 计算WOE值

In [11]:
def calcu_woe(Data,bins_seq):
    woe_dict = {}
    for col in Data.columns.tolist(): 
        woe_List =[]
        if col=='SeriousDlqin2yrs':
            Allgood = Data[col].value_counts()[1]
            Allbad = Data[col].value_counts()[0]
        else:
            for i in np.arange(len(bins_seq[col])-1):
                Min =Data[col]<=bins_seq[col][i+1]
                Max =Data[col]>bins_seq[col][i]
                good = Data.loc[(Min&Max),'SeriousDlqin2yrs'].sum()
                bad = len(Data.loc[(Min&Max),'SeriousDlqin2yrs'])-good
                woe = np.log((good/Allgood)*(Allbad/bad))
                woe_List.append(round(woe,4))
            woe_dict[col] =woe_List
    return woe_dict

In [42]:
woe_dict =calcu_woe(data_Smote,bins_seq)
woe_dict

{'RevolvingUtilizationOfUnsecuredLines': [0.8288,
  1.1802,
  -0.1158,
  -1.0818,
  -2.2233,
  -0.4941],
 'age': [-0.5688, -0.3553, -0.1361, 0.2853, 0.5439, 0.9594, 1.1947],
 'NumberOfTime30-59DaysPastDueNotWorse': [0.5275,
  -0.9063,
  -1.7379,
  -2.3839,
  -2.6572],
 'DebtRatio': [0.0129, -0.0005, -0.7209, 0.0224, 0.4969, 0.1871],
 'MonthlyIncome': [0.2474, -0.3321, -0.2824, -0.092, 0.1839, 0.4113],
 'NumberOfOpenCreditLinesAndLoans': [-1.3749, -0.7978, -0.2559, 0.025, 0.1242],
 'NumberOfTimes90DaysLate': [0.3751, -1.9657, -2.6376, -3.0776, -3.3085],
 'NumberRealEstateLoansOrLines': [-0.0232, 0.1844, -0.2586],
 'NumberOfTime60-89DaysPastDueNotWorse': [0.2729,
  -1.833,
  -2.6953,
  -3.1007,
  -3.3874],
 'NumberOfDependents': [0.1553, -0.0996, -0.2373, -0.4537, -0.7082]}

# 对整个数据集进行cut切分

In [13]:
Data_Cut = pd.DataFrame()
def Data_Preprocessing_Cut(Data,bins_seq):
    for col in list(Data.columns[1:]):
        Data_Cut[col] = pd.cut(data_Smote[col],bins =bins_seq[col]).map(str).tolist()
    return Data_Cut

In [14]:
Data_Smote_Cut = Data_Preprocessing_Cut(data_Smote,bins_seq=bins_seq)

# 用WOE数据替换原数据集

In [15]:
def data_preprocessing_woereplace(Source_data,Source_data_cut,Bins_seq,Woe_dict):
    # first step . use woe values and binning make dict for replace
    Data = Source_data.copy()
    for col in Data.columns.tolist()[1:]:
        woe_bins_dict ={}
        bins_sort_list = pd.cut(Data[col],bins =bins_seq[col]).unique().sort_values().tolist()
        for i,bins in enumerate(bins_sort_list):
            woe_bins_dict[str(bins)] = woe_dict[col][i]
        Data[col] = Data_Smote_Cut[col].map(woe_bins_dict)
    return Data

In [16]:
Data_Smote_Cut_replace = data_preprocessing_woereplace(Source_data=data_Smote,Source_data_cut=Data_Smote_Cut,Bins_seq=bins_seq,Woe_dict=woe_dict)

In [17]:
Data_Smote_Cut_replace.to_csv('Data_Smote_Cut_replace.csv',header = True,index=False,encoding='utf-8')

In [28]:
class class_Preprocess_WOE_Reshape:
    def __init__(self,data,bins):
        self.Data = data
        self.bins = bins
    def calcu_woe(self):
        woe_dict = {}
        for col in self.Data.columns.tolist(): 
            woe_List =[]
            if col=='SeriousDlqin2yrs':
                Allgood = self.Data[col].value_counts()[1]
                Allbad = self.Data[col].value_counts()[0]
            else:
                for i in np.arange(len(self.bins[col])-1):
                    Min =self.Data[col]<=self.bins[col][i+1]
                    Max =self.Data[col]>self.bins[col][i]
                    good = self.Data.loc[(Min&Max),'SeriousDlqin2yrs'].sum()
                    bad = len(self.Data.loc[(Min&Max),'SeriousDlqin2yrs'])-good
                    woe = np.log((good/Allgood)*(Allbad/bad))
                    woe_List.append(round(woe,4))
                woe_dict[col] =woe_List
        return woe_dict
    def Data_Preprocessing_Cut(self):
        Data_Cut = pd.DataFrame()
        for col in list( self.Data.columns[1:]):
            Data_Cut[col] = pd.cut( self.Data[col],bins =self.bins[col]).map(str).tolist()
        return Data_Cut
    def data_Preprocessing_Woe_Replace(self):
        # first step . use woe values and binning make dict for replace
        Data = self.Data.copy()
        for col in Data.columns.tolist()[1:]:
            woe_bins_dict ={}
            woe_dict = calcu_woe(Data=self.Data,bins_seq=self.bins)
            Data_Smote_Cut = Data_Preprocessing_Cut(Data=self.Data,bins_seq=self.bins)
            bins_sort_list = pd.cut(Data[col],bins =self.bins[col]).unique().sort_values().tolist()
            for i,bins in enumerate(bins_sort_list):
                woe_bins_dict[str(bins)] = woe_dict[col][i]
            Data[col] = Data_Smote_Cut[col].map(woe_bins_dict)
        return Data

In [29]:
WOE_Reshape = class_Preprocess_WOE_Reshape(data = data_Smote,bins=bins_seq)
woe_dict = WOE_Reshape.calcu_woe()

In [30]:
woe_dict = WOE_Reshape.calcu_woe()
Data_Cut = WOE_Reshape.Data_Preprocessing_Cut()

In [43]:
woe_dict

{'RevolvingUtilizationOfUnsecuredLines': [0.8288,
  1.1802,
  -0.1158,
  -1.0818,
  -2.2233,
  -0.4941],
 'age': [-0.5688, -0.3553, -0.1361, 0.2853, 0.5439, 0.9594, 1.1947],
 'NumberOfTime30-59DaysPastDueNotWorse': [0.5275,
  -0.9063,
  -1.7379,
  -2.3839,
  -2.6572],
 'DebtRatio': [0.0129, -0.0005, -0.7209, 0.0224, 0.4969, 0.1871],
 'MonthlyIncome': [0.2474, -0.3321, -0.2824, -0.092, 0.1839, 0.4113],
 'NumberOfOpenCreditLinesAndLoans': [-1.3749, -0.7978, -0.2559, 0.025, 0.1242],
 'NumberOfTimes90DaysLate': [0.3751, -1.9657, -2.6376, -3.0776, -3.3085],
 'NumberRealEstateLoansOrLines': [-0.0232, 0.1844, -0.2586],
 'NumberOfTime60-89DaysPastDueNotWorse': [0.2729,
  -1.833,
  -2.6953,
  -3.1007,
  -3.3874],
 'NumberOfDependents': [0.1553, -0.0996, -0.2373, -0.4537, -0.7082]}

In [32]:
Target_data = WOE_Reshape.data_Preprocessing_Woe_Replace()

In [41]:
Target_data[:3]

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines     age  \
0                 0                               -1.0818 -0.3553   
1                 1                               -1.0818 -0.3553   
2                 1                               -0.1158 -0.3553   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                               -1.7379    -0.0005         0.4113   
1                                0.5275    -0.0005        -0.3321   
2                               -0.9063    -0.0005        -0.2824   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                           0.1242                   0.3751   
1                           0.0250                   0.3751   
2                          -0.2559                  -1.9657   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                       -0.2586                                0.2729   
1                       -0.0232                                0.2729   
2                       -0.0232                                0.2729   

   NumberOfDependents  
0             -0.2373  
1             -0.0996  
2              0.1553